name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.x
          otp-version: 25.x
      - name: Install Xvfb
        run: |
          sudo apt-get install xvfb
      - name: Start Xvfb
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Resolve elixir-ls dependencies
        run: |
          cd elixir-ls
          mix deps.get
      - name: Resolve vscode-elixir-ls dependencies
        run: |
          npm install
          npm run lint
          npm run check-formatting
          npm run compile
      - name: Run tests
        run: |
          npm test
        env:
          DISPLAY: :99.0
