on:
  push:
    tags:
      - "*"

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: validate version
        run: |
          VERSION=$(jq -r .version package.json)
          if [[ "$GITHUB_REF_NAME" != "v$VERSION" ]]; then
              echo "package.json version $VERSION does not match commit tag $GITHUB_REF_NAME"
              exit 1
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.x
          otp-version: 25.x
      - run: npm ci
      - run: mix deps.get
        
      - name: set publisher for Open VSX Registry
        run: |
          jq '.publisher = "JakeBecker"' package.json > package_temp.json
          mv package_temp.json package.json
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: ${{ contains(github.ref, '-rc.') }}
      - name: set publisher for Open VSX Registry
        run: |
          jq '.publisher = "elixir-lsp"' package.json > package_temp.json
          mv package_temp.json package.json
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          preRelease: ${{ contains(github.ref, '-rc.') }}
